// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5wScl54SDSsio9NXHk-26zVbc9b_bjqk',
    appId: '1:1093070321011:android:3ca1dadb2e7c73996cc106',
    messagingSenderId: '1093070321011',
    projectId: 'bytebank-2778e',
    storageBucket: 'bytebank-2778e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxq7FRyBAhQyuGvsd5iT2k9XebCgNFfqo',
    appId: '1:1093070321011:ios:eec8e4131fecade46cc106',
    messagingSenderId: '1093070321011',
    projectId: 'bytebank-2778e',
    storageBucket: 'bytebank-2778e.firebasestorage.app',
    iosBundleId: 'com.example.bytebankApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClM5-T_xxRH7uigNE9fAlhrowvTCdwg-A',
    appId: '1:1093070321011:web:38af7fc39837a7826cc106',
    messagingSenderId: '1093070321011',
    projectId: 'bytebank-2778e',
    authDomain: 'bytebank-2778e.firebaseapp.com',
    storageBucket: 'bytebank-2778e.firebasestorage.app',
    measurementId: 'G-3NV064BHR3',
  );

}